export const ACCESS_METHODS = ['RSS', 'FIXTURE', 'UNSUPPORTED'] as const
export type AccessMethod = (typeof ACCESS_METHODS)[number]

export const COLLECTOR_STATUSES = ['FUNCTIONAL', 'PLACEHOLDER', 'UNSUPPORTED'] as const
export type CollectorStatus = (typeof COLLECTOR_STATUSES)[number]

export const SCAN_STATUSES = ['RUNNING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED'] as const
export type ScanStatus = (typeof SCAN_STATUSES)[number]

export const PARSE_STATUSES = ['PARSED', 'UNSUPPORTED', 'ERROR'] as const
export type ParseStatus = (typeof PARSE_STATUSES)[number]

export const CLAIM_TYPES = [
  'EXECUTIVE_CHANGE',
  'HIRING_CHANGE',
  'FINANCIAL_RESULT',
  'LAYOFF_MENTION',
  'FUNDING_MENTION',
  'PRODUCT_LAUNCH',
  'PRODUCT_FAILURE',
  'LEGAL_EVENT',
  'REGULATORY_EVENT',
  'SUPPLY_CHAIN_EVENT',
  'MACRO_EVENT',
  'SENTIMENT_EVENT',
  'PROCUREMENT_EVENT',
  'MARKET_DEMAND_EVENT',
  'UNKNOWN',
] as const
export type ClaimType = (typeof CLAIM_TYPES)[number]

export const SIGNAL_TYPES = [
  'HIRING_ACCELERATION',
  'HIRING_SLOWDOWN',
  'EXECUTIVE_EXIT',
  'EXECUTIVE_HIRE',
  'LAYOFF_SIGNAL',
  'FUNDING_SIGNAL',
  'CASH_PRESSURE',
  'LEGAL_PRESSURE',
  'CUSTOMER_COMPLAINT_SPIKE',
  'PRODUCT_MOMENTUM',
  'PRODUCT_DECAY',
  'MACRO_PRESSURE',
  'SECTOR_PRESSURE',
  'SUPPLY_CHAIN_PRESSURE',
  'REGULATORY_PRESSURE',
  'PROCUREMENT_INCREASE',
  'DEMAND_SPIKE',
  'TALENT_MARKET_SHIFT',
  'UNKNOWN',
] as const
export type SignalType = (typeof SIGNAL_TYPES)[number]

export const DIRECTIONS = ['POSITIVE', 'NEGATIVE', 'NEUTRAL', 'MIXED', 'UNKNOWN'] as const
export type Direction = (typeof DIRECTIONS)[number]

export const EVENT_CLASSES = ['RISK', 'OPPORTUNITY', 'MIXED', 'WATCH', 'UNKNOWN'] as const
export type EventClass = (typeof EVENT_CLASSES)[number]

export const EVENT_STATUSES = [
  'NEW',
  'RISING',
  'STABLE',
  'DECLINING',
  'CONFIRMED',
  'DISMISSED',
  'ESCALATED',
  'NEEDS_REVIEW',
] as const
export type EventStatus = (typeof EVENT_STATUSES)[number]

export const FEED_TYPES = ['RISK_RADAR', 'OPPORTUNITY_RADAR', 'INBOX', 'WATCHLIST'] as const
export type FeedType = (typeof FEED_TYPES)[number]

export const SOURCE_HEALTH_STATUSES = ['HEALTHY', 'DEGRADED', 'FAILING', 'UNSUPPORTED', 'UNKNOWN'] as const
export type SourceHealthStatus = (typeof SOURCE_HEALTH_STATUSES)[number]

export const OPPORTUNITY_TYPES = [
  'SALES', 'PARTNERSHIP', 'PROCUREMENT', 'INVESTMENT_WATCH', 'HIRING',
  'TALENT_ACQUISITION', 'M_AND_A', 'CONTENT', 'ADVISORY', 'PRODUCT_GAP',
  'MARKET_ENTRY', 'COMPETITOR_DISPLACEMENT', 'COMPLIANCE', 'CRISIS_SUPPORT',
] as const
export type OpportunityType = (typeof OPPORTUNITY_TYPES)[number]

export const OPPORTUNITY_STATUSES = [
  'NEW', 'RISING', 'STABLE', 'DECLINING', 'DISMISSED', 'ESCALATED', 'ACTIONED',
] as const
export type OpportunityStatus = (typeof OPPORTUNITY_STATUSES)[number]

export const POSITIONING_USER_TYPES = [
  'SUPPLIER', 'RECRUITER', 'PRODUCT_TEAM', 'PROCUREMENT', 'INVESTOR_WATCH',
  'ADVISOR', 'ANALYST', 'GENERAL',
] as const
export type PositioningUserType = (typeof POSITIONING_USER_TYPES)[number]

export const RISK_APPETITES = ['LOW', 'MEDIUM', 'HIGH'] as const
export type RiskAppetite = (typeof RISK_APPETITES)[number]

export const NODE_TYPES = [
  'EVENT','SOURCE','DOCUMENT','CLAIM','SIGNAL','COMPANY','SECTOR','COMMODITY',
  'INSTRUMENT','PERSON','REGION','REGULATION','PROCUREMENT','RISK','OPPORTUNITY',
  'POSITIONING','CONTRADICTION','DATA_GAP',
] as const
export type NodeType = (typeof NODE_TYPES)[number]

export const EDGE_TYPES = [
  'REPORTED_BY','DERIVED_FROM','SUPPORTS','CONTRADICTS','AFFECTS','EXPOSES',
  'AMPLIFIES','WEAKENS','CAUSES_PRESSURE_ON','CREATES_OPPORTUNITY_FOR',
  'LINKED_TO','PRICED_BY','REGULATED_BY','SUPPLIED_BY','DEPENDS_ON','COMPETES_WITH',
] as const
export type EdgeType = (typeof EDGE_TYPES)[number]

export const ARC_CLASSES = [
  'STRONG_CHAIN','WEAK_SIGNAL','WIDELY_REPEATED_WEAK_SOURCE','CONTRADICTED',
  'HIGH_POTENTIAL_LOW_CONFIDENCE',
] as const
export type ArcClass = (typeof ARC_CLASSES)[number]

export const QUERY_TYPES = [
  'COMPANY','COMMODITY','INSTRUMENT','TICKER','SHARE_PRICE','SECTOR','REGION',
  'THEME','REGULATION','PROCUREMENT','UNKNOWN',
] as const
export type QueryType = (typeof QUERY_TYPES)[number]

export const LLM_TASK_TYPES = [
  'CLAIM_EXTRACTION_ASSIST','ENTITY_RESOLUTION_ASSIST','SIGNAL_CLASSIFICATION_ASSIST',
  'CONTRADICTION_ANALYSIS','EVIDENCE_ARC_SUMMARY','STRATEGIC_POSITIONING_GENERATION',
  'OPPORTUNITY_PLAYBOOK_GENERATION','EXECUTIVE_BRIEF_GENERATION','GRAPH_NODE_SUMMARY',
  'GRAPH_EDGE_EXPLANATION','MARKET_CONTEXT_SYNTHESIS','RISK_OPPORTUNITY_SYNTHESIS',
  'OUTREACH_DRAFT_GENERATION','TRANSLATION','LONG_CONTEXT_REVIEW','FAST_CLASSIFICATION','SAFETY_REVIEW',
] as const
export type LLMTaskType = (typeof LLM_TASK_TYPES)[number]

export const LLM_RUN_STATUSES = ['PENDING','SUCCEEDED','FAILED','SKIPPED_NO_PROVIDER','REJECTED_VALIDATION'] as const
export type LLMRunStatus = (typeof LLM_RUN_STATUSES)[number]

export const VALIDATION_STATUSES = ['PASSED','FAILED','NOT_RUN'] as const
export type ValidationStatus = (typeof VALIDATION_STATUSES)[number]

export const PLAYBOOK_GENERATORS = ['DETERMINISTIC','LLM'] as const
export type PlaybookGenerator = (typeof PLAYBOOK_GENERATORS)[number]

export const MARKET_RESULT_TYPES = ['INSTRUMENT','COMMODITY','COMPANY','NONE'] as const
export type MarketResultType = (typeof MARKET_RESULT_TYPES)[number]

export const INSTRUMENT_TYPES = ['EQUITY','ETF','INDEX','FX','FUTURE','BOND','CRYPTO','UNKNOWN'] as const
export type InstrumentType = (typeof INSTRUMENT_TYPES)[number]

export const COMMODITY_CATEGORIES = ['METAL','ENERGY','AGRICULTURE','LIVESTOCK','INDUSTRIAL','OTHER'] as const
export type CommodityCategory = (typeof COMMODITY_CATEGORIES)[number]

export const MARKET_PROVIDER_STATUSES = ['CONFIGURED','NOT_CONFIGURED'] as const
export type MarketProviderStatus = (typeof MARKET_PROVIDER_STATUSES)[number]

export const PORTFOLIO_STATUSES = ['NEW','INVESTIGATING','QUALIFIED','REJECTED','ACTING','WON','LOST','WATCHING'] as const
export type PortfolioStatus = (typeof PORTFOLIO_STATUSES)[number]

export const GRAPH_EVENT_TYPES = [
  'FIRST_DETECTED','NEW_SOURCE','CLAIM_REPEATED','SIGNAL_STRENGTHENED','CONTRADICTION_DETECTED',
  'OPPORTUNITY_GENERATED','CONFIDENCE_ROSE','CONFIDENCE_FELL','EVENT_COOLED','EVENT_ESCALATED',
] as const
export type GraphEventType = (typeof GRAPH_EVENT_TYPES)[number]

export const GRAPH_SNAPSHOT_TYPES = ['EVENT_FORMATION','CURRENT_STATE','MANUAL'] as const
export type GraphSnapshotType = (typeof GRAPH_SNAPSHOT_TYPES)[number]
