/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as TrackRecordRouteImport } from './routes/track-record'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as ScansRouteImport } from './routes/scans'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as InterrogationsRouteImport } from './routes/interrogations'
import { Route as InterrogateRouteImport } from './routes/interrogate'
import { Route as ExposuresRouteImport } from './routes/exposures'
import { Route as DigestRouteImport } from './routes/digest'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as BriefingsRouteImport } from './routes/briefings'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as AskGraphRouteImport } from './routes/ask-graph'
import { Route as ArcsRouteImport } from './routes/arcs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities.index'
import { Route as SourcesIdRouteImport } from './routes/sources.$id'
import { Route as SettingsScanRouteImport } from './routes/settings.scan'
import { Route as SettingsDeliveryRouteImport } from './routes/settings.delivery'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities.$id'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as CompaniesNameRouteImport } from './routes/companies.$name'
import { Route as ArcsIdRouteImport } from './routes/arcs.$id'
import { Route as AdminRoutingRouteImport } from './routes/admin.routing'
import { Route as ApiPublicHooksScanRouteImport } from './routes/api/public/hooks/scan'
import { Route as ApiPublicHooksBriefingRouteImport } from './routes/api/public/hooks/briefing'
import { Route as ApiPublicExportsEventsRouteImport } from './routes/api/public/exports/events'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRecordRoute = TrackRecordRouteImport.update({
  id: '/track-record',
  path: '/track-record',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansRoute = ScansRouteImport.update({
  id: '/scans',
  path: '/scans',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const InterrogationsRoute = InterrogationsRouteImport.update({
  id: '/interrogations',
  path: '/interrogations',
  getParentRoute: () => rootRouteImport,
} as any)
const InterrogateRoute = InterrogateRouteImport.update({
  id: '/interrogate',
  path: '/interrogate',
  getParentRoute: () => rootRouteImport,
} as any)
const ExposuresRoute = ExposuresRouteImport.update({
  id: '/exposures',
  path: '/exposures',
  getParentRoute: () => rootRouteImport,
} as any)
const DigestRoute = DigestRouteImport.update({
  id: '/digest',
  path: '/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingsRoute = BriefingsRouteImport.update({
  id: '/briefings',
  path: '/briefings',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const AskGraphRoute = AskGraphRouteImport.update({
  id: '/ask-graph',
  path: '/ask-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcsRoute = ArcsRouteImport.update({
  id: '/arcs',
  path: '/arcs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpportunitiesRoute,
} as any)
const SourcesIdRoute = SourcesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SourcesRoute,
} as any)
const SettingsScanRoute = SettingsScanRouteImport.update({
  id: '/settings/scan',
  path: '/settings/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDeliveryRoute = SettingsDeliveryRouteImport.update({
  id: '/settings/delivery',
  path: '/settings/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OpportunitiesRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesNameRoute = CompaniesNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => CompaniesRoute,
} as any)
const ArcsIdRoute = ArcsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArcsRoute,
} as any)
const AdminRoutingRoute = AdminRoutingRouteImport.update({
  id: '/admin/routing',
  path: '/admin/routing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksScanRoute = ApiPublicHooksScanRouteImport.update({
  id: '/api/public/hooks/scan',
  path: '/api/public/hooks/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksBriefingRoute = ApiPublicHooksBriefingRouteImport.update({
  id: '/api/public/hooks/briefing',
  path: '/api/public/hooks/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExportsEventsRoute = ApiPublicExportsEventsRouteImport.update({
  id: '/api/public/exports/events',
  path: '/api/public/exports/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arcs': typeof ArcsRouteWithChildren
  '/ask-graph': typeof AskGraphRoute
  '/backtest': typeof BacktestRoute
  '/briefings': typeof BriefingsRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/digest': typeof DigestRoute
  '/exposures': typeof ExposuresRoute
  '/interrogate': typeof InterrogateRoute
  '/interrogations': typeof InterrogationsRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/review': typeof ReviewRoute
  '/scans': typeof ScansRoute
  '/sources': typeof SourcesRouteWithChildren
  '/track-record': typeof TrackRecordRoute
  '/watchlist': typeof WatchlistRoute
  '/admin/routing': typeof AdminRoutingRoute
  '/arcs/$id': typeof ArcsIdRoute
  '/companies/$name': typeof CompaniesNameRoute
  '/events/$id': typeof EventsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/settings/delivery': typeof SettingsDeliveryRoute
  '/settings/scan': typeof SettingsScanRoute
  '/sources/$id': typeof SourcesIdRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/api/public/exports/events': typeof ApiPublicExportsEventsRoute
  '/api/public/hooks/briefing': typeof ApiPublicHooksBriefingRoute
  '/api/public/hooks/scan': typeof ApiPublicHooksScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arcs': typeof ArcsRouteWithChildren
  '/ask-graph': typeof AskGraphRoute
  '/backtest': typeof BacktestRoute
  '/briefings': typeof BriefingsRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/digest': typeof DigestRoute
  '/exposures': typeof ExposuresRoute
  '/interrogate': typeof InterrogateRoute
  '/interrogations': typeof InterrogationsRoute
  '/review': typeof ReviewRoute
  '/scans': typeof ScansRoute
  '/sources': typeof SourcesRouteWithChildren
  '/track-record': typeof TrackRecordRoute
  '/watchlist': typeof WatchlistRoute
  '/admin/routing': typeof AdminRoutingRoute
  '/arcs/$id': typeof ArcsIdRoute
  '/companies/$name': typeof CompaniesNameRoute
  '/events/$id': typeof EventsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/settings/delivery': typeof SettingsDeliveryRoute
  '/settings/scan': typeof SettingsScanRoute
  '/sources/$id': typeof SourcesIdRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/api/public/exports/events': typeof ApiPublicExportsEventsRoute
  '/api/public/hooks/briefing': typeof ApiPublicHooksBriefingRoute
  '/api/public/hooks/scan': typeof ApiPublicHooksScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arcs': typeof ArcsRouteWithChildren
  '/ask-graph': typeof AskGraphRoute
  '/backtest': typeof BacktestRoute
  '/briefings': typeof BriefingsRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/digest': typeof DigestRoute
  '/exposures': typeof ExposuresRoute
  '/interrogate': typeof InterrogateRoute
  '/interrogations': typeof InterrogationsRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/review': typeof ReviewRoute
  '/scans': typeof ScansRoute
  '/sources': typeof SourcesRouteWithChildren
  '/track-record': typeof TrackRecordRoute
  '/watchlist': typeof WatchlistRoute
  '/admin/routing': typeof AdminRoutingRoute
  '/arcs/$id': typeof ArcsIdRoute
  '/companies/$name': typeof CompaniesNameRoute
  '/events/$id': typeof EventsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/settings/delivery': typeof SettingsDeliveryRoute
  '/settings/scan': typeof SettingsScanRoute
  '/sources/$id': typeof SourcesIdRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/api/public/exports/events': typeof ApiPublicExportsEventsRoute
  '/api/public/hooks/briefing': typeof ApiPublicHooksBriefingRoute
  '/api/public/hooks/scan': typeof ApiPublicHooksScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arcs'
    | '/ask-graph'
    | '/backtest'
    | '/briefings'
    | '/companies'
    | '/digest'
    | '/exposures'
    | '/interrogate'
    | '/interrogations'
    | '/opportunities'
    | '/review'
    | '/scans'
    | '/sources'
    | '/track-record'
    | '/watchlist'
    | '/admin/routing'
    | '/arcs/$id'
    | '/companies/$name'
    | '/events/$id'
    | '/opportunities/$id'
    | '/settings/delivery'
    | '/settings/scan'
    | '/sources/$id'
    | '/opportunities/'
    | '/api/public/exports/events'
    | '/api/public/hooks/briefing'
    | '/api/public/hooks/scan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arcs'
    | '/ask-graph'
    | '/backtest'
    | '/briefings'
    | '/companies'
    | '/digest'
    | '/exposures'
    | '/interrogate'
    | '/interrogations'
    | '/review'
    | '/scans'
    | '/sources'
    | '/track-record'
    | '/watchlist'
    | '/admin/routing'
    | '/arcs/$id'
    | '/companies/$name'
    | '/events/$id'
    | '/opportunities/$id'
    | '/settings/delivery'
    | '/settings/scan'
    | '/sources/$id'
    | '/opportunities'
    | '/api/public/exports/events'
    | '/api/public/hooks/briefing'
    | '/api/public/hooks/scan'
  id:
    | '__root__'
    | '/'
    | '/arcs'
    | '/ask-graph'
    | '/backtest'
    | '/briefings'
    | '/companies'
    | '/digest'
    | '/exposures'
    | '/interrogate'
    | '/interrogations'
    | '/opportunities'
    | '/review'
    | '/scans'
    | '/sources'
    | '/track-record'
    | '/watchlist'
    | '/admin/routing'
    | '/arcs/$id'
    | '/companies/$name'
    | '/events/$id'
    | '/opportunities/$id'
    | '/settings/delivery'
    | '/settings/scan'
    | '/sources/$id'
    | '/opportunities/'
    | '/api/public/exports/events'
    | '/api/public/hooks/briefing'
    | '/api/public/hooks/scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArcsRoute: typeof ArcsRouteWithChildren
  AskGraphRoute: typeof AskGraphRoute
  BacktestRoute: typeof BacktestRoute
  BriefingsRoute: typeof BriefingsRoute
  CompaniesRoute: typeof CompaniesRouteWithChildren
  DigestRoute: typeof DigestRoute
  ExposuresRoute: typeof ExposuresRoute
  InterrogateRoute: typeof InterrogateRoute
  InterrogationsRoute: typeof InterrogationsRoute
  OpportunitiesRoute: typeof OpportunitiesRouteWithChildren
  ReviewRoute: typeof ReviewRoute
  ScansRoute: typeof ScansRoute
  SourcesRoute: typeof SourcesRouteWithChildren
  TrackRecordRoute: typeof TrackRecordRoute
  WatchlistRoute: typeof WatchlistRoute
  AdminRoutingRoute: typeof AdminRoutingRoute
  EventsIdRoute: typeof EventsIdRoute
  SettingsDeliveryRoute: typeof SettingsDeliveryRoute
  SettingsScanRoute: typeof SettingsScanRoute
  ApiPublicExportsEventsRoute: typeof ApiPublicExportsEventsRoute
  ApiPublicHooksBriefingRoute: typeof ApiPublicHooksBriefingRoute
  ApiPublicHooksScanRoute: typeof ApiPublicHooksScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-record': {
      id: '/track-record'
      path: '/track-record'
      fullPath: '/track-record'
      preLoaderRoute: typeof TrackRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans': {
      id: '/scans'
      path: '/scans'
      fullPath: '/scans'
      preLoaderRoute: typeof ScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interrogations': {
      id: '/interrogations'
      path: '/interrogations'
      fullPath: '/interrogations'
      preLoaderRoute: typeof InterrogationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interrogate': {
      id: '/interrogate'
      path: '/interrogate'
      fullPath: '/interrogate'
      preLoaderRoute: typeof InterrogateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exposures': {
      id: '/exposures'
      path: '/exposures'
      fullPath: '/exposures'
      preLoaderRoute: typeof ExposuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digest': {
      id: '/digest'
      path: '/digest'
      fullPath: '/digest'
      preLoaderRoute: typeof DigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefings': {
      id: '/briefings'
      path: '/briefings'
      fullPath: '/briefings'
      preLoaderRoute: typeof BriefingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask-graph': {
      id: '/ask-graph'
      path: '/ask-graph'
      fullPath: '/ask-graph'
      preLoaderRoute: typeof AskGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcs': {
      id: '/arcs'
      path: '/arcs'
      fullPath: '/arcs'
      preLoaderRoute: typeof ArcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof OpportunitiesRoute
    }
    '/sources/$id': {
      id: '/sources/$id'
      path: '/$id'
      fullPath: '/sources/$id'
      preLoaderRoute: typeof SourcesIdRouteImport
      parentRoute: typeof SourcesRoute
    }
    '/settings/scan': {
      id: '/settings/scan'
      path: '/settings/scan'
      fullPath: '/settings/scan'
      preLoaderRoute: typeof SettingsScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/delivery': {
      id: '/settings/delivery'
      path: '/settings/delivery'
      fullPath: '/settings/delivery'
      preLoaderRoute: typeof SettingsDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof OpportunitiesRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$name': {
      id: '/companies/$name'
      path: '/$name'
      fullPath: '/companies/$name'
      preLoaderRoute: typeof CompaniesNameRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/arcs/$id': {
      id: '/arcs/$id'
      path: '/$id'
      fullPath: '/arcs/$id'
      preLoaderRoute: typeof ArcsIdRouteImport
      parentRoute: typeof ArcsRoute
    }
    '/admin/routing': {
      id: '/admin/routing'
      path: '/admin/routing'
      fullPath: '/admin/routing'
      preLoaderRoute: typeof AdminRoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scan': {
      id: '/api/public/hooks/scan'
      path: '/api/public/hooks/scan'
      fullPath: '/api/public/hooks/scan'
      preLoaderRoute: typeof ApiPublicHooksScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/briefing': {
      id: '/api/public/hooks/briefing'
      path: '/api/public/hooks/briefing'
      fullPath: '/api/public/hooks/briefing'
      preLoaderRoute: typeof ApiPublicHooksBriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/exports/events': {
      id: '/api/public/exports/events'
      path: '/api/public/exports/events'
      fullPath: '/api/public/exports/events'
      preLoaderRoute: typeof ApiPublicExportsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ArcsRouteChildren {
  ArcsIdRoute: typeof ArcsIdRoute
}

const ArcsRouteChildren: ArcsRouteChildren = {
  ArcsIdRoute: ArcsIdRoute,
}

const ArcsRouteWithChildren = ArcsRoute._addFileChildren(ArcsRouteChildren)

interface CompaniesRouteChildren {
  CompaniesNameRoute: typeof CompaniesNameRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesNameRoute: CompaniesNameRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

interface OpportunitiesRouteChildren {
  OpportunitiesIdRoute: typeof OpportunitiesIdRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
}

const OpportunitiesRouteChildren: OpportunitiesRouteChildren = {
  OpportunitiesIdRoute: OpportunitiesIdRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
}

const OpportunitiesRouteWithChildren = OpportunitiesRoute._addFileChildren(
  OpportunitiesRouteChildren,
)

interface SourcesRouteChildren {
  SourcesIdRoute: typeof SourcesIdRoute
}

const SourcesRouteChildren: SourcesRouteChildren = {
  SourcesIdRoute: SourcesIdRoute,
}

const SourcesRouteWithChildren =
  SourcesRoute._addFileChildren(SourcesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArcsRoute: ArcsRouteWithChildren,
  AskGraphRoute: AskGraphRoute,
  BacktestRoute: BacktestRoute,
  BriefingsRoute: BriefingsRoute,
  CompaniesRoute: CompaniesRouteWithChildren,
  DigestRoute: DigestRoute,
  ExposuresRoute: ExposuresRoute,
  InterrogateRoute: InterrogateRoute,
  InterrogationsRoute: InterrogationsRoute,
  OpportunitiesRoute: OpportunitiesRouteWithChildren,
  ReviewRoute: ReviewRoute,
  ScansRoute: ScansRoute,
  SourcesRoute: SourcesRouteWithChildren,
  TrackRecordRoute: TrackRecordRoute,
  WatchlistRoute: WatchlistRoute,
  AdminRoutingRoute: AdminRoutingRoute,
  EventsIdRoute: EventsIdRoute,
  SettingsDeliveryRoute: SettingsDeliveryRoute,
  SettingsScanRoute: SettingsScanRoute,
  ApiPublicExportsEventsRoute: ApiPublicExportsEventsRoute,
  ApiPublicHooksBriefingRoute: ApiPublicHooksBriefingRoute,
  ApiPublicHooksScanRoute: ApiPublicHooksScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
